---
title: "Plotly Examples"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

My name is Keyi and I make website _with interactive graphics_

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

## let's make some plots

```{r}
data("instacart")
```


```{r}
instacart %>%
select(aisle_id) %>%
  count(aisle_id) %>%
mutate(
  number_of_item = n
) %>%
  arrange(desc(number_of_item)) %>%
  filter(number_of_item > 15000) %>%
  mutate(
   aisle_id = factor(aisle_id),
  aisle_id = forcats::fct_reorder(aisle_id, number_of_item )) %>%
 ggplot(aes(x = aisle_id, y = number_of_item,color = aisle_id))+
  geom_col() +
  labs(
    title = "Plot of Aisles Ordered More Than 10000 Items",
    x = "Aisle ID",
    y = "Number of Items Ordered"
  ) 

```

```{r}




```

```{r}
instacart %>%
select(department,order_hour_of_day,aisle) %>%
arrange(order_hour_of_day)%>%
group_by(department,order_hour_of_day)%>%
count(aisle)%>%
group_by(department,order_hour_of_day)%>%
summarize(number_ordered = sum(n)) %>%
  ggplot(aes(x = order_hour_of_day,
             y = number_ordered,color = department)) +
  geom_line() +
  labs(
    title = " Plot of Number of Items Odered with 24h among Departments ",
    x = "Hour in a day",
    y = "Number Of Items ordered"
  )

```

